# Generated by Django 5.0.3 on 2024-04-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='image_url',
            field=models.URLField(default='https://stock.adobe.com/search?k=spoon'),
        ),
    ]
